name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r linux-musl-x64 --self-contained true -o publish/ SomeTestApp.Web/SomeTestApp.Web.csproj
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: some-test-app
        path: publish/
    - name: Create ZIP archive
      run: zip -r SomeTestApp.zip publish/
    - name: Send File via SSH
      run: |
        SECRET_CONTENT="${{ secrets.SSH_PRIVATE_KEY }}"
        echo "$SECRET_CONTENT" > private.key
        scp -i private.key -P ${{ secrets.SSH_PORT }} SomeTestApp.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}